spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infou_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

# Additional settings for better logging and debugging
#  main:
#    allow-bean-definition-overriding: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  sql:
#    init:
#      mode: always

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: trace

